version: '3.8'

services:
  backend:
    build:
      context: ./Backend  # Use a relative path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontend  # Use a relative path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
