# Use an official Python runtime as a parent image
FROM python:3.11.4-slim

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the backend directory into the container at /app/
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the FastAPI app when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


